# Generated by Django 3.0.5 on 2020-07-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover_pic',
        ),
    ]
